server:
  port: 8888
spring:
  application:
    name: config-server
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/chaubes/config-server-properties.git'
          searchPaths: 'config/{application}/{profile}'
          cloneOnStart: true
          default-label: master
          force-pull: true
          timeout: 10

